author: Nuno Aguiar, Andreia Brizida, Jose Alves, Leandro Fernandes
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- raid
- s3
- nattrmon
bugs:
  url: https://github.com/OpenAF/nAttrMon-configs/issues
repository:
  type: http
  url: https://openaf.io/opacks/nAttrMon.opack
description: Config packages for nAttrMon
name: nAttrMon
main: ''
mainJob: ''
license: Apache 2.0 license
version: '20211024'
dependencies:
  openaf: '>=20210721'
files:
- README.md
- .package.yaml
- nAttrMon/objects/nInput_nAttrMon.js
- utils/createConfig.yaml
- S3/inputs.disabled/01.s3.buckets.yaml
- S3/inputs.disabled/00.init.s3.yaml
- S3/objects/nInput_S3Buckets.js
- S3/objects/nInput_S3Init.js
- RAID/objects/nInput_WELCache.js
- RAID/objects/nInput_BPMDebugChecks.js
- RAID/objects/nInput_ProcessManager.js
- RAID/objects/nInput_CBPMSemaphores.js
- RAID/objects/nInput_CBPMFlowManager.js
- RAID/objects/nInput_RAIDSQLs.js
- RAID/objects/nInput_RAIDQueryManager.js
- RAID/objects/nInput_DMPerformance.js
- RAID/objects/nInput_RAIDGCMemory.js
- RAID/objects/nInput_CBPMRunningFlows.js
- RAID/objects/nInput_RAIDMemory.js
- RAID/objects/nInput_BPMNRunningFlows.js
- RAID/objects/nInput_CBPMFlowStore.js
- RAID/objects/nInput_Schedulers.js
- RAID/objects/nInput_RAIDLookups.js
- RAID/objects/nInput_AFPing.js
- RAID/objects/nInput_RAIDStatus_DB.js
- RAID/objects/nInput_CBPMDebugChecks.js
- RAID/objects/nInput_Semaphores.js
- LICENSE
filesHash:
  README.md: d39ac664fdea882cf3bcb89570768aeba3a86891
  nAttrMon/objects/nInput_nAttrMon.js: c8ec9f45f724e7372b02751b893178490587641b
  utils/createConfig.yaml: 0ebe179909750bc9e4ab6a25d009d9abda375dc8
  S3/inputs.disabled/01.s3.buckets.yaml: 25319586b67bc3bc5977f929a2a1690264db7315
  S3/inputs.disabled/00.init.s3.yaml: 8ad83a626a1ee36cf57812f2b0d948745fa945a2
  S3/objects/nInput_S3Buckets.js: 93c577ed77b99d6cc0b8770d0dfb46db010c7acd
  S3/objects/nInput_S3Init.js: 33cbd0b1c12f01e3d95b69a74e5257424474d652
  RAID/objects/nInput_WELCache.js: d20e0fdc2d08f6273e25cc8a8b513be41f7207cd
  RAID/objects/nInput_BPMDebugChecks.js: 6e1042ba95cc3374d3516be2202538529344769f
  RAID/objects/nInput_ProcessManager.js: d1e3a3bfe34af52ff05ba623742dfd3979bf2484
  RAID/objects/nInput_CBPMSemaphores.js: 75a0892cdad21aee8762d6d1346548bf6d42b59b
  RAID/objects/nInput_CBPMFlowManager.js: 5128f64828ee2f9296376931a7a8dae80ff74aed
  RAID/objects/nInput_RAIDSQLs.js: 370e0fb53d8255c755bc3f7a8b8f9c082ad6c9bb
  RAID/objects/nInput_RAIDQueryManager.js: e17fad0c68b57f547544ba3b67c053bb3fa21bf9
  RAID/objects/nInput_DMPerformance.js: 3d0f27b87f5b1a004e32559b0076c3cbfdf5d064
  RAID/objects/nInput_RAIDGCMemory.js: 61db6bc880acfd8ce0845b2a604f403bc3f26730
  RAID/objects/nInput_CBPMRunningFlows.js: 54156f08ebcd272a24ae0b7d8c135f5d582dd195
  RAID/objects/nInput_RAIDMemory.js: 5b941a58ef1b523d3f5825435ecfb72dabb7143c
  RAID/objects/nInput_BPMNRunningFlows.js: 86da2d78b524d42ac4ab9598820605bbbfb24c57
  RAID/objects/nInput_CBPMFlowStore.js: c0ca266117bde6a9a4456c6eba31e1fede9c5ca5
  RAID/objects/nInput_Schedulers.js: 96771d166e2574b6d5a526cc6025ad3abf1363d4
  RAID/objects/nInput_RAIDLookups.js: 1544374c0bec3e6c53eb60c1efe578f4b8f101ae
  RAID/objects/nInput_AFPing.js: c88598e75deb073715ed011272ae7ffb46962e8e
  RAID/objects/nInput_RAIDStatus_DB.js: a59c7b62281341e3b0a3e279ff12eaaa85b43eac
  RAID/objects/nInput_CBPMDebugChecks.js: 737f33ddd852309d0322f57e7adeeb307627652f
  RAID/objects/nInput_Semaphores.js: 9b0c0d8ca1b1c33d8faeaae89738360c8569534e
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
