name: Update package

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  workflow_dispatch:

jobs:

  updateOPack:
    runs-on: ubuntu-latest
    steps  :
    # -------------------------
    - uses: actions/checkout@v2
    # --------------------
    - name: Install openaf
      run : |
        curl https://openaf.io/install.sh | sh
    # ------------------
    - name: Update opack
      run : |
        cd $GITHUB_WORKSPACE && opack genpack . --exclude .github
    # ---------------------
    - name: Commit and push
      run : |
        git config --global user.name 'OpenAF'
        git config --global user.email 'openaf@users.noreply.github.com'
        git add .package.yaml
        git diff --quiet && git diff --staged --quiet || git commit -am "Update package"
        git push
